
version: '3.8'

services:
  # MongoDB Database Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  # Backend Node.js Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./server/uploads:/usr/src/app/uploads
    environment:
      - MONGO_URI=mongodb://mongodb:27017/bitacoraGrowDB
      - PORT=3000
      - JWT_SECRET=your_super_secret_key_change_this
    depends_on:
      - mongodb
    restart: unless-stopped

  # Frontend Angular Service (served with Nginx)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80" # Access the app at http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
